#ifndef _STK_DEFAULT_H_
#define _STK_DEFAULT_H_

#include "SDL.h"

#define STK_LABEL_DEFAULT_WIDTH		60
#define STK_LABEL_DEFAULT_HEIGHT	30

#define STK_BUTTON_BORDER_THICKNESS	2

#define STK_RADIOBUTTON_BORDER_THICKNESS	2

#define STK_RADIOGROUP_BORDER_THICKNESS	2
#define STK_RADIOBUTTON_DEFAULT_WIDTH		100
#define STK_RADIOBUTTON_DEFAULT_HEIGHT		25

#define STK_ENTRY_BORDER_THICKNESS	3
#define STK_ENTRY_CURSOR_WIDTH		2

#define STK_SLIDEBAR_BORDER_THICKNESS 2

#define STK_PROGRESSBAR_BORDER_THICKNESS	2

#define STK_MSGBOX_BORDER_THICKNESS	4


#endif /* _STK_DEFAULT_H_ */
